/**
 * HYDRAX website — the link hub's STATIC FALLBACK links (/links).
 *
 * THIS IS NO LONGER THE AUTHORING SURFACE. The link hub is edited in the
 * admin CMS ("Link Hub" in the left-hand nav at /admin), and published CMS
 * content is what /links renders at runtime. See docs/CMS.md §"Link hub".
 *
 * What this file is for now — two things, both of which need it to stay
 * exactly as it is unless the page's *defaults* genuinely change:
 *
 *   1. The offline/no-CMS render. js/links.js applies these values
 *      immediately on load and only then overlays published CMS content, so
 *      a visitor whose request for /api/v1/website-content fails still gets
 *      a complete, correct page rather than a blank one.
 *   2. The seed. backend/src/domain/website-content-seed.ts's `linkHub`
 *      section is transcribed from this file, and that is what a fresh
 *      database is populated with on first boot.
 *
 * THREE SURFACES, KEPT IN AGREEMENT BY CHECKS — not by anyone remembering:
 *   - this file  <->  links.html's no-JS markup     : website/check.mjs
 *   - this file  <->  the backend seed              : backend/test/website-content.test.ts
 * Change one without the others and those fail, naming exactly what drifted.
 * So do NOT edit this file to change live content — that is what the CMS is
 * for, and an edit here would not even be what visitors see.
 *
 * ---------------------------------------------------------------------------
 * THE RULE THAT MATTERS: every entry below is a REAL destination that already
 * exists in this repository. There are no placeholder URLs, and there must
 * never be one.
 *
 * HYDRAX has no LinkedIn page, no Instagram, no Facebook, no YouTube, no
 * TikTok and no X account — not "not linked yet", but genuinely nonexistent
 * as far as anything in this repository knows. A bio link that 404s costs
 * more trust than an absent row does, so those rows are absent rather than
 * guessed. `SOCIAL_PLATFORMS` below carries the presentation for each of
 * those platforms with NO url; an admin adds a real one through the CMS,
 * which validates the host before accepting it.
 * ---------------------------------------------------------------------------
 */

/** The single primary call to action, rendered as the one filled button. */
export const PRIMARY_LINK = {
  href: '/',
  label: 'Visit the HYDRAX website',
  note: 'What the system is, how it works, and what it deliberately does not do',
};

/**
 * Product and project destinations, in display order. All internal routes on
 * this same site — the server resolves extensionless paths (see
 * backend/src/http/static.ts), which is why these carry no `.html`.
 */
export const PROJECT_LINKS = [
  {
    href: '/request',
    label: 'Request a HYDRAX System',
    note: 'Tell us about your farm — no account, no payment, no obligation',
  },
  {
    href: '/dashboard',
    label: 'Live monitoring dashboard',
    note: 'Soil moisture, irrigation state, pump health, alerts',
  },
];

/**
 * Social accounts.
 *
 * `url: null` means the account does not exist, and the row is not rendered.
 * The label and icon are kept ready so that publishing one later is a
 * one-line change rather than a design exercise — but a null here is a
 * statement of fact, not a TODO to fill in with a guess.
 *
 * `icon` names a key in js/links.js's ICONS registry. `domain` is the host a
 * real URL for that platform must be on — check.mjs uses it both to reject a
 * profile URL pointing somewhere else and to prove no row for an account that
 * does not exist has slipped onto the page.
 */
export const SOCIAL_PLATFORMS = [
  { key: 'linkedin', label: 'Team LinkedIn', icon: 'linkedin', domain: 'linkedin.com', url: null },
  { key: 'instagram', label: 'Instagram', icon: 'instagram', domain: 'instagram.com', url: null },
  { key: 'facebook', label: 'Facebook', icon: 'facebook', domain: 'facebook.com', url: null },
  { key: 'youtube', label: 'YouTube', icon: 'youtube', domain: 'youtube.com', url: null },
  { key: 'tiktok', label: 'TikTok', icon: 'tiktok', domain: 'tiktok.com', url: null },
  { key: 'x', label: 'X', icon: 'x', domain: 'x.com', url: null },
];

/**
 * Contact methods — the same address and number the rest of the site shows
 * (index.html's #contact, privacy.html and terms.html). `display` is what a
 * visitor reads; `href` is what the phone dials. The number is shown in the
 * local-dial form the site already uses and dialled in international form,
 * which is exactly what index.html does.
 */
export const CONTACT_LINKS = [
  {
    href: 'mailto:ingeniummteam@email.com',
    label: 'Email us',
    display: 'ingeniummteam@email.com',
    icon: 'mail',
  },
  {
    href: 'tel:+201279159200',
    label: 'Call us',
    display: '0127 915 9200',
    icon: 'phone',
  },
];

/** Not a link — stated because a farm product is judged partly on being local. */
export const LOCATION = 'Mansoura, Egypt';

/**
 * Every social row currently publishable: the platforms with a real URL.
 * Empty today, by design — see the rule at the top of this file.
 */
export function publishableSocials() {
  return SOCIAL_PLATFORMS.filter(
    (platform) => typeof platform.url === 'string' && platform.url.trim() !== '',
  );
}

/* ---------------------------------------------------------------------------
 * ADDING A SOCIAL ACCOUNT (once one genuinely exists)
 *
 * Through the CMS — no code change, no deploy:
 *   1. /admin -> "Website content" tab -> "Link Hub" in the left nav.
 *   2. Under "Social accounts", paste the real profile URL next to that
 *      platform. The server accepts it only if it is https and its host is
 *      that platform's own domain, so a LinkedIn row cannot point elsewhere.
 *   3. Save draft -> Preview (shows /links with the draft) -> Save & publish.
 *
 * The row appears on /links the moment it is published, and the "Follow"
 * section appears with it. Until then the section renders nothing at all.
 *
 * Editing this file instead would only change the offline fallback and the
 * seed for a *fresh* database — not what visitors currently see — and would
 * fail the drift checks named at the top of this file.
 * ------------------------------------------------------------------------- */
